--- QUICC CONSULT

ALTER DEFAULT PRIVILEGES IN SCHEMA domtar_pp GRANT SELECT ON TABLES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_bsl GRANT SELECT ON TABLES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_sys_class_qc GRANT SELECT ON TABLES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA nb_pp GRANT SELECT ON TABLES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA on_pp GRANT SELECT ON TABLES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_pp GRANT SELECT ON TABLES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_tp GRANT SELECT ON TABLES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA temp_quicc GRANT SELECT ON TABLES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA us_pp GRANT SELECT ON TABLES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA rdb_quicc GRANT SELECT ON TABLES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA clim_rs GRANT SELECT ON TABLES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_world GRANT SELECT ON TABLES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_qc GRANT SELECT ON TABLES TO "QUICC_CONSULT";

ALTER DEFAULT PRIVILEGES IN SCHEMA domtar_pp GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_bsl GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_sys_class_qc GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA nb_pp GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA on_pp GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_pp GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_tp GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA temp_quicc GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA us_pp GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA rdb_quicc GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA clim_rs GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_world GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_qc GRANT SELECT ON SEQUENCES TO "QUICC_CONSULT";

ALTER DEFAULT PRIVILEGES IN SCHEMA domtar_pp GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_bsl GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_sys_class_qc GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA nb_pp GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA on_pp GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_pp GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_tp GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA temp_quicc GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA us_pp GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA rdb_quicc GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA clim_rs GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_world GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_qc GRANT EXECUTE ON FUNCTIONS TO "QUICC_CONSULT";

ALTER DEFAULT PRIVILEGES IN SCHEMA domtar_pp GRANT USAGE ON TYPES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_bsl GRANT USAGE ON TYPES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_sys_class_qc GRANT USAGE ON TYPES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA nb_pp GRANT USAGE ON TYPES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA on_pp GRANT USAGE ON TYPES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_pp GRANT USAGE ON TYPES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_tp GRANT USAGE ON TYPES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA temp_quicc GRANT USAGE ON TYPES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA us_pp GRANT USAGE ON TYPES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA rdb_quicc GRANT USAGE ON TYPES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA clim_rs GRANT USAGE ON TYPES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_world GRANT USAGE ON TYPES TO "QUICC_CONSULT";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_qc GRANT USAGE ON TYPES TO "QUICC_CONSULT";

-- QUICC

ALTER DEFAULT PRIVILEGES IN SCHEMA domtar_pp GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_bsl GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_sys_class_qc GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA nb_pp GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA on_pp GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_pp GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_tp GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA temp_quicc GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA us_pp GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA rdb_quicc GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA clim_rs GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_world GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_qc GRANT ALL PRIVILEGES ON TABLES TO "QUICC" WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA domtar_pp GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_bsl GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_sys_class_qc GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA nb_pp GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA on_pp GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_pp GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_tp GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA temp_quicc GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA us_pp GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA rdb_quicc GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA clim_rs GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_world GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_qc GRANT ALL PRIVILEGES ON SEQUENCES TO "QUICC" WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA domtar_pp GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_bsl GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_sys_class_qc GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA nb_pp GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA on_pp GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_pp GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_tp GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA temp_quicc GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA us_pp GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA rdb_quicc GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA clim_rs GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_world GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_qc GRANT ALL PRIVILEGES ON FUNCTIONS TO "QUICC" WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA domtar_pp GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_bsl GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_sys_class_qc GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA nb_pp GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA on_pp GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_pp GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA qc_tp GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA temp_quicc GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA us_pp GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA rdb_quicc GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA clim_rs GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_world GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;
ALTER DEFAULT PRIVILEGES IN SCHEMA map_qc GRANT ALL PRIVILEGES ON TYPES TO "QUICC" WITH GRANT OPTION;

-- QUICC_MAP

ALTER DEFAULT PRIVILEGES IN SCHEMA map_bsl GRANT SELECT ON TABLES TO "QUICC_MAP";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_sys_class_qc GRANT SELECT ON TABLES TO "QUICC_MAP";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_world GRANT SELECT ON TABLES TO "QUICC_MAP";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_qc GRANT SELECT ON TABLES TO "QUICC_MAP";

ALTER DEFAULT PRIVILEGES IN SCHEMA map_bsl GRANT SELECT ON SEQUENCES TO "QUICC_MAP";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_sys_class_qc GRANT SELECT ON SEQUENCES TO "QUICC_MAP";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_world GRANT SELECT ON SEQUENCES TO "QUICC_MAP";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_qc GRANT SELECT ON SEQUENCES TO "QUICC_MAP";

ALTER DEFAULT PRIVILEGES IN SCHEMA map_bsl GRANT EXECUTE ON FUNCTIONS TO "QUICC_MAP";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_sys_class_qc GRANT EXECUTE ON FUNCTIONS TO "QUICC_MAP";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_world GRANT EXECUTE ON FUNCTIONS TO "QUICC_MAP";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_qc GRANT EXECUTE ON FUNCTIONS TO "QUICC_MAP";

ALTER DEFAULT PRIVILEGES IN SCHEMA map_bsl GRANT USAGE ON TYPES TO "QUICC_MAP";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_sys_class_qc GRANT USAGE ON TYPES TO "QUICC_MAP";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_world GRANT USAGE ON TYPES TO "QUICC_MAP";
ALTER DEFAULT PRIVILEGES IN SCHEMA map_qc GRANT USAGE ON TYPES TO "QUICC_MAP";

-- QUICC_CLIM

ALTER DEFAULT PRIVILEGES IN SCHEMA clim_rs GRANT SELECT ON TABLES TO "QUICC_CLIM";
ALTER DEFAULT PRIVILEGES IN SCHEMA clim_rs GRANT SELECT ON SEQUENCES TO "QUICC_CLIM";
ALTER DEFAULT PRIVILEGES IN SCHEMA clim_rs GRANT EXECUTE ON FUNCTIONS TO "QUICC_CLIM";
ALTER DEFAULT PRIVILEGES IN SCHEMA clim_rs GRANT USAGE ON TYPES TO "QUICC_CLIM";
